### ISSUE TITLE
Which version to use with lagom 1.5.4

### ISSUE THREAD

**Issue by nikhilaroratgo** [SwissBorg/lithium#131]
I am using Lagom 1.5.4 which uses scala 2.12 and akka 2.5
I tried to add the swizz borg dependency but it fails due to incompatible akka version

            <dependency>
                <groupId>com.swissborg</groupId>
                <artifactId>lithium_2.12</artifactId>
                <version>0.11.2</version>
            </dependency>

During the startup the app fails
```
Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.5.25 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.   
```

which versions should I use with lagom 1.5.4 ?
Should I exclude the transitive dependency of akka 2.6 from lithium? Will the downing provider work with akka 2.5?

**Comment by nikhilaroratgo** [comment]
I see that version 0.95 supports akka 2.5. Can this be used if I plan to use keep-majority and keep-oldest strategies?
Are there some major improvements done afterwards which would makes 0.95 release risky to use in Production?

**Comment by DennisVDB** [comment]
There were some significant improvements since 0.95, I wouldn't use it in production. 
From what I remember Akka didn't change anything Lithium relied on between 2.5 and 2.6. Excluding it as a transitive dependency might work but make sure to test.

**Comment by nikhilaroratgo** [comment]
allright, thanks
